### ISSUE TITLE
will rt-wifi maintained in future?

### ISSUE THREAD

**Issue by roboticsai** [AlexisTM/RT-WiFi#1]
I am trying to use this code as to control the robot wirelessly in real time, but since like this project is no longer maintained and the latest linux kernel is also not working while building. So what should i do?

**Comment by AlexisTM** [comment]
Well, I kept this as an archive as I am not the author.

This repo is the wifi-kernel the project was based on followed by the code giving the full diff for a better understanding of the modifications.

Unless there is a community or the project is used/baked by a company, every project will eventually die and break over time.

What I would do if I were you is to create a community around Real Time communication technologies and bring the people interested together. Keep track of all the methods proposed with pros/cons to make a new one that will be maintained by the community. 

As for new developments, I would try to do the project in two parts: 
- Expose all the absolutely required options from the kernel by updating the current implementation of MAC80211 and keeping it to a minimum to allow to apply it with high chance of success on newer kernels and have a tiny chance to be actually merged into the main kernel.
- A module that doesn't require any kernel modifications once you applied the (small) kernel patch.

**Comment by liu-jeff** [comment]
Please ask if RT-WiFi is successfully applied to high version kernels and high version drivers such as ath10k?

**Comment by AlexisTM** [comment]
This is an archive, I am not the author nor maintainer.
